# Example_Server:
#   type: http | minecraft
#   cron: '0 * * * *'
#   url: http://example.com/
#   response:
#     # Use only one expected response type
#     # Default expected response type is `code: 200`
#
#     code: 200
#     body: Online
#     json_body:
#       value: 1  # Use 0/1 for boolean values
#       keys: 
#       - status
#       - online
#   alert:
#     email: user@example.com

services:
  Minecraft_Server:
    type: minecraft
    cron: '* * * * *'
    # url: https://api.mcsrvstat.us/simple/mc.haddock.cloud:9999
    ip: play.wynncraft.com
    failure_log_level: CRITICAL
